-- 插入測試資料到 DEPARTMENTS 表
INSERT INTO DEPARTMENTS (DEPT_NO, NAME, LOCATION) VALUES (1, 'HR', 'New York');
INSERT INTO DEPARTMENTS (DEPT_NO, NAME, LOCATION) VALUES (2, 'Finance', 'London');
INSERT INTO DEPARTMENTS (DEPT_NO, NAME, LOCATION) VALUES (3, 'IT', 'San Francisco');
COMMIT;
