CREATE OR REPLACE TRIGGER  DEPARTMENTS_BIU
    BEFORE INSERT OR UPDATE ON DEPARTMENTS
    FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.DEPT_NO IS NULL THEN
        :NEW.DEPT_NO := TO_NUMBER(SYS_GUID(), 
          'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    END IF;
END;
/

CREATE OR REPLACE TRIGGER EMPLOYEES_BIU
    BEFORE INSERT OR UPDATE ON EMPLOYEES
    FOR EACH ROW
BEGIN
    IF INSERTING AND :NEW.EMP_NO IS NULL THEN
        :NEW.EMP_NO := TO_NUMBER(SYS_GUID(), 
            'XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX');
    END IF;
END;
/